<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>doctorSelectionSearchBox</name>
   <tag></tag>
   <elementGuidId>93cafbc0-42b4-4c1d-baac-2ccdcafc1b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/span[1]/span[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/span[1]/span[1]/span[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
