<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tpaPanelSelectionSearchBox</name>
   <tag></tag>
   <elementGuidId>97351196-635e-4a26-bb61-547e954ad26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/span[1]/span[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/span[1]/span[1]/span[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
