<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>visitTypeDropdownOTC</name>
   <tag></tag>
   <elementGuidId>c39e8073-aaf3-4bf7-a0c4-1b739380a73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[contains(text(),'OTC')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//option[contains(text(),'OTC')]</value>
   </webElementProperties>
</WebElementEntity>
