<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logoutBtn</name>
   <tag></tag>
   <elementGuidId>6449246c-96da-4638-8901-d7595bcb53af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='app']/div[2]/nav[1]/div[1]/div[3]/ul[1]/li[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='app']/div[2]/nav[1]/div[1]/div[3]/ul[1]/li[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
