<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>patientDetailsName</name>
   <tag></tag>
   <elementGuidId>987e1fe4-8ec7-478a-80bb-bd899341baa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//strong[text()=&quot;${PATNAME}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[text()=&quot;${PATNAME}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
