<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>patientDetailsPhoneNo</name>
   <tag></tag>
   <elementGuidId>f8435248-9441-45ed-b713-1d2fafbc234d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(),'${EMAIL}')]//parent::tr//preceding-sibling::tr[1]//td[contains(text(),'${PHONENO}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(),'${EMAIL}')]//parent::tr//preceding-sibling::tr[1]//td[contains(text(),'${PHONENO}')]</value>
   </webElementProperties>
</WebElementEntity>
