<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invoiceDisposableDropdownSelect</name>
   <tag></tag>
   <elementGuidId>c00804b3-02a3-4195-a573-053517e2118c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/div[5]/div[2]/div[1]/div[1]/div[1]/div[2]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/div[5]/div[2]/div[1]/div[1]/div[1]/div[2]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
