<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invoiceProcedureDropdownOption</name>
   <tag></tag>
   <elementGuidId>c16f70a2-30bc-4e3d-9b30-3a2d951edeec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/div[4]/div[2]/div[1]/div[1]/div[1]/div[2]/select[1]/option[contains(text(),'Circumcision')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/div[4]/div[2]/div[1]/div[1]/div[1]/div[2]/select[1]/option[contains(text(),'Circumcision')]</value>
   </webElementProperties>
</WebElementEntity>
