<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>patientNewEncounterMedicationDescriptionSelect</name>
   <tag></tag>
   <elementGuidId>73435666-363d-4dc1-8516-19be6b1acbe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='app']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/form[1]/div[4]/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='app']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/form[1]/div[4]/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
