<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>patientNewEncounterEncounterExamInputField</name>
   <tag></tag>
   <elementGuidId>7f7a7c62-e7d4-4fb4-a820-ad641e5c1998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/form[1]/div[4]/div[4]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/form[1]/div[4]/div[4]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/textarea[1]</value>
   </webElementProperties>
</WebElementEntity>
