<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>queuePatientPharmacyCounter</name>
   <tag></tag>
   <elementGuidId>ff228eb4-557a-4ca7-b2d9-910394521437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='app']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/a[1]/div[contains(text(),'Pharmacy')]/following-sibling::div[contains(text(),'1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='app']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/a[1]/div[contains(text(),'Pharmacy')]/following-sibling::div[contains(text(),'1')]</value>
   </webElementProperties>
</WebElementEntity>
