<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appointmentSMS30MinsReminder</name>
   <tag></tag>
   <elementGuidId>dfe31a20-bf8e-4a8d-a032-3a54ff10116a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[8]/td[1]/input[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[8]/td[1]/input[3]</value>
   </webElementProperties>
</WebElementEntity>
