<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appointmentRemarksInputField</name>
   <tag></tag>
   <elementGuidId>4df61326-e499-495a-ab48-ab4bd73b2b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[6]/td[1]/textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[6]/td[1]/textarea[1]</value>
   </webElementProperties>
</WebElementEntity>
