<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detailsPatientEmailInputField</name>
   <tag></tag>
   <elementGuidId>e5fac06e-9212-4981-993f-381c797f4f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[contains(text(),'Email')]//following-sibling::td//child::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[contains(text(),'Email')]//following-sibling::td//child::input</value>
   </webElementProperties>
</WebElementEntity>
